name: Spring Boot CI/CD with Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스 코드 Checkout
      - name: Checkout
        uses: actions/checkout@v3

      # 2. JDK 21 설정 (<<<<< 변경된 부분)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      # 4. Gradle로 빌드
      # (CI 단계에서 Java 21로 빌드 및 테스트 실행)
      - name: Build with Gradle
        run: ./gradlew build

      # 5. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # 6. Docker 이미지 빌드 및 푸시
      - name: Get Git Commit SHA
        id: git-sha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile  # 위에서 수정한 Dockerfile 사용
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            ${{ secrets.DOCKER_USERNAME }}/my-spring-app:${{ steps.git-sha.outputs.sha }}

      # 7. 배포 서버에 SSH 접속하여 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            docker stop my-spring-app || true
            docker rm my-spring-app || true
            docker run -d -p 8080:8080 --name my-spring-app \
              -e SPRING_DATASOURCE_URL=${{ secrets.DB_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest