version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app-deploy
    overwrite: true

permissions:
  - object: /home/ubuntu/app-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
  # 아래의 scripts 관련 중복 설정 삭제함

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu