version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app-deploy # 배포 스크립트가 위치할 경로
    overwrite: true

permissions:
  - object: /home/ubuntu/app-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
  - object: /home/ubuntu/app-deploy/scripts
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
