-- 반품·교환 클레임(35 설계서 1-1 · 1-4 · 앱 클레임 설계서 1-1 · 1-2).
--
-- 요청(= 한 박스 = order_claim_collection)과 항목(order_claim)을 가른다. 사유 · 회수 송장 · 수취 주소 · 배송비는 요청에,
-- 상태 · 검수 판정은 항목에 있다. 접수번호는 컬럼을 두지 않는다 — CLM-{claim_id}.

CREATE TABLE `order_claim_collection` (
    `collection_id`         BIGINT        NOT NULL AUTO_INCREMENT,
    `order_id`              BIGINT        NOT NULL,
    `delivery_group_id`     BIGINT        NOT NULL COMMENT '한 묶음 = 한 하위주문 안의 항목들',
    `market_id`             BIGINT        NOT NULL,
    `user_id`               BIGINT        NOT NULL,
    `type`                  VARCHAR(16)   NOT NULL COMMENT 'RETURN, EXCHANGE — 요청에 하나',
    `reason_code`           VARCHAR(40)   NOT NULL,
    `reason_detail`         VARCHAR(1000) NULL,
    `fee_bearer`            VARCHAR(16)   NOT NULL COMMENT 'CONSUMER, SELLER — 신청 시점 값',
    `idempotency_key`       VARCHAR(64)   NULL,
    `carrier`               VARCHAR(30)   NULL COMMENT '회수 송장 — 소비자 입력',
    `tracking_number`       VARCHAR(50)   NULL,
    `invoice_registered_at` DATETIME(6)   NULL COMMENT '입력 시각 = 회수 중 전환. 정정으로 바뀌지 않는다',
    `invoice_due_at`        DATETIME(6)   NOT NULL COMMENT '회수 송장 등록 기한 — 지나면 자동 취소',
    `last_tracking_at`      DATETIME(6)   NULL,
    `last_tracking_label`   VARCHAR(100)  NULL,
    `arrived_at`            DATETIME(6)   NULL COMMENT '추적상 브랜드 도착 — 입고 확인과 따로 저장',
    `return_recipient`      VARCHAR(64)   NULL COMMENT '반품 수취 주소 스냅샷 — 신청 시점의 마켓 출고지',
    `return_contact`        VARCHAR(20)   NULL,
    `return_address`        VARCHAR(255)  NULL,
    `return_detail_address` VARCHAR(255)  NULL,
    `return_deduction`      INT           NOT NULL DEFAULT 0 COMMENT '반품 배송비 차감액 — 요청당 한 번',
    `reship_recipient`      VARCHAR(64)   NULL COMMENT '재발송 수취지 스냅샷 — 기본은 원 주문 배송지',
    `reship_phone`          VARCHAR(20)   NULL,
    `reship_zip_code`       VARCHAR(10)   NULL,
    `reship_address`        VARCHAR(255)  NULL,
    `reship_detail_address` VARCHAR(255)  NULL,
    `reship_memo`           VARCHAR(255)  NULL,
    `refund_amount`         INT           NULL COMMENT '요청의 판정이 다 끝난 순간 확정되는 환불액',
    `finalized_at`          DATETIME(6)   NULL,
    `created_at`            DATETIME(6)   NOT NULL,
    PRIMARY KEY (`collection_id`),
    CONSTRAINT `uk_order_claim_collection_idempotency` UNIQUE (`user_id`, `idempotency_key`),
    KEY `idx_order_claim_collection_group` (`delivery_group_id`),
    KEY `idx_order_claim_collection_invoice_due` (`invoice_due_at`),
    CONSTRAINT `fk_order_claim_collection_group` FOREIGN KEY (`delivery_group_id`)
        REFERENCES `order_delivery_group` (`delivery_group_id`),
    CONSTRAINT `fk_order_claim_collection_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `order_claim` (
    `claim_id`               BIGINT        NOT NULL AUTO_INCREMENT COMMENT '접수번호 = CLM-{claim_id}',
    `collection_id`          BIGINT        NOT NULL,
    `order_id`               BIGINT        NOT NULL,
    `delivery_group_id`      BIGINT        NOT NULL,
    `order_product_id`       BIGINT        NOT NULL,
    `market_id`              BIGINT        NOT NULL,
    `user_id`                BIGINT        NOT NULL,
    `type`                   VARCHAR(16)   NOT NULL COMMENT 'RETURN, EXCHANGE',
    `quantity`               INT           NOT NULL,
    `reason_code`            VARCHAR(40)   NOT NULL COMMENT '요청의 사본 — 목록 필터용',
    `reason_detail`          VARCHAR(1000) NULL,
    `fee_bearer`             VARCHAR(16)   NOT NULL,
    `exchange_variant_id`    BIGINT        NULL,
    `exchange_option_name`   VARCHAR(255)  NULL,
    `status`                 VARCHAR(30)   NOT NULL,
    `stage_entered_at`       DATETIME(6)   NOT NULL COMMENT '현재 상태 진입 시각',
    `requested_at`           DATETIME(6)   NOT NULL,
    `collect_due_at`         DATETIME(6)   NOT NULL COMMENT '기한 ① — 신청 + 2영업일',
    `received_at`            DATETIME(6)   NULL,
    `received_by`            BIGINT        NULL,
    `inspect_due_at`         DATETIME(6)   NULL COMMENT '기한 ② — 입고 확인 때 발급',
    `inspected_at`           DATETIME(6)   NULL,
    `inspected_by`           BIGINT        NULL,
    `reject_reason_code`     VARCHAR(30)   NULL,
    `reject_detail`          VARCHAR(1000) NULL,
    `rejected_at`            DATETIME(6)   NULL COMMENT '재발송 사유 · 구매확정 보류 해제의 판별자',
    `notice_count`           INT           NOT NULL DEFAULT 0 COMMENT '미결제 고지 횟수 — order_claim_notice 의 집계 캐시',
    `last_notice_at`         DATETIME(6)   NULL COMMENT '보관 기한의 기산점',
    `reship_carrier`         VARCHAR(30)   NULL,
    `reship_tracking_number` VARCHAR(50)   NULL,
    `reship_registered_at`   DATETIME(6)   NULL,
    `reship_registered_by`   BIGINT        NULL,
    `reship_last_tracking_at` DATETIME(6)  NULL,
    `reship_delivered_at`    DATETIME(6)   NULL,
    `result`                 VARCHAR(16)   NULL COMMENT 'REFUNDED, EXCHANGED, REJECTED, CANCELLED — COMPLETED 일 때만',
    `cancel_reason`          VARCHAR(20)   NULL COMMENT 'WITHDRAWN, INVOICE_EXPIRED, ADMIN',
    `completed_at`           DATETIME(6)   NULL,
    `refunded_amount`        INT           NULL COMMENT '운영자가 집행한 확정액',
    `disposed_at`            DATETIME(6)   NULL COMMENT '거절 종결이 보관 기간 만료 후 폐기였을 때',
    PRIMARY KEY (`claim_id`),
    KEY `idx_order_claim_market_status` (`market_id`, `status`, `stage_entered_at`),
    KEY `idx_order_claim_product` (`order_product_id`),
    KEY `idx_order_claim_group_status` (`delivery_group_id`, `status`),
    KEY `idx_order_claim_collection` (`collection_id`),
    KEY `idx_order_claim_reship` (`status`, `reship_registered_at`),
    KEY `idx_order_claim_reship_invoice` (`reship_carrier`, `reship_tracking_number`),
    CONSTRAINT `fk_order_claim_collection` FOREIGN KEY (`collection_id`)
        REFERENCES `order_claim_collection` (`collection_id`),
    CONSTRAINT `fk_order_claim_group` FOREIGN KEY (`delivery_group_id`)
        REFERENCES `order_delivery_group` (`delivery_group_id`),
    CONSTRAINT `fk_order_claim_product` FOREIGN KEY (`order_product_id`) REFERENCES `order_product` (`order_product_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
