/* 1. MARKET_SNS 테이블 생성 */
CREATE TABLE MARKET_SNS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    MARKET_ID BIGINT NOT NULL,
    SNS_TYPE VARCHAR(50) NOT NULL,
    SNS_URL VARCHAR(512) NOT NULL,
    
    /* 외래키 제약조건 (필요 시 FK 이름 변경) */
    CONSTRAINT FK_MARKET_SNS_MARKET 
        FOREIGN KEY (MARKET_ID) REFERENCES MARKET (MARKET_ID)
        ON DELETE CASCADE
);

/* 2. 기존 데이터 마이그레이션 (TYPE|URL 파싱) */
-- SNS_LINK_1 데이터 이전
INSERT INTO MARKET_SNS (MARKET_ID, SNS_TYPE, SNS_URL)
SELECT 
    MARKET_ID, 
    SUBSTRING_INDEX(SNS_LINK_1, '|', 1), -- 구분자 앞부분 (TYPE)
    SUBSTRING_INDEX(SNS_LINK_1, '|', -1) -- 구분자 뒷부분 (URL)
FROM MARKET 
WHERE SNS_LINK_1 IS NOT NULL AND SNS_LINK_1 != '';

-- SNS_LINK_2 데이터 이전
INSERT INTO MARKET_SNS (MARKET_ID, SNS_TYPE, SNS_URL)
SELECT 
    MARKET_ID, 
    SUBSTRING_INDEX(SNS_LINK_2, '|', 1), 
    SUBSTRING_INDEX(SNS_LINK_2, '|', -1)
FROM MARKET 
WHERE SNS_LINK_2 IS NOT NULL AND SNS_LINK_2 != '';

-- SNS_LINK_3 데이터 이전
INSERT INTO MARKET_SNS (MARKET_ID, SNS_TYPE, SNS_URL)
SELECT 
    MARKET_ID, 
    SUBSTRING_INDEX(SNS_LINK_3, '|', 1), 
    SUBSTRING_INDEX(SNS_LINK_3, '|', -1)
FROM MARKET 
WHERE SNS_LINK_3 IS NOT NULL AND SNS_LINK_3 != '';

/* 3. 기존 컬럼 삭제 */
ALTER TABLE MARKET DROP COLUMN SNS_LINK_1;
ALTER TABLE MARKET DROP COLUMN SNS_LINK_2;
ALTER TABLE MARKET DROP COLUMN SNS_LINK_3;