/* 1. SELLER 테이블에 ACTIVITY_NAME 컬럼 추가 (NULL 허용) */
ALTER TABLE SELLER 
ADD COLUMN ACTIVITY_NAME VARCHAR(100) DEFAULT NULL;

/* 2. MARKET 테이블에 MARKET_TYPE 컬럼 추가 */
ALTER TABLE MARKET 
ADD COLUMN MARKET_TYPE VARCHAR(20);

/* 3. 기존 MARKET 데이터의 MARKET_TYPE을 'MARKET'으로 일괄 업데이트 */
UPDATE MARKET 
SET MARKET_TYPE = 'MARKET' 
WHERE MARKET_TYPE IS NULL;

/* 4. MARKET_TYPE 업데이트 완료 후 NOT NULL 제약조건 추가 (필수 권장) */
ALTER TABLE MARKET 
MODIFY COLUMN MARKET_TYPE VARCHAR(20) NOT NULL;