-- 사업자 기본 정보 추가
ALTER TABLE SELLER
ADD COLUMN BUSINESS_TYPE VARCHAR(50),
ADD COLUMN REPRESENTATIVE_NAME VARCHAR(64),
ADD COLUMN REPRESENTATIVE_CONTACT VARCHAR(20),
ADD COLUMN COMPANY_NAME VARCHAR(100),
ADD COLUMN BUSINESS_REG_NUMBER VARCHAR(20),
ADD COLUMN BUSINESS_CONDITION VARCHAR(100),
ADD COLUMN BUSINESS_ADDRESS VARCHAR(255),
ADD COLUMN DETAIL_ADDRESS VARCHAR(255),
ADD COLUMN TAX_EMAIL VARCHAR(512),
ADD COLUMN BUSINESS_LICENSE_URL VARCHAR(1024),
ADD COLUMN MAIL_ORDER_REG_URL VARCHAR(1024),
ADD COLUMN MAIL_ORDER_REG_NUM VARCHAR(100),

-- 정산 계좌 정보 추가
ADD COLUMN BANK_NAME VARCHAR(50),
ADD COLUMN ACCOUNT_HOLDER VARCHAR(64),
ADD COLUMN ACCOUNT_NUMBER VARCHAR(100),
ADD COLUMN BANKBOOK_URL VARCHAR(1024),

-- 약관 동의 내역 추가
ADD COLUMN AGREE_PRIVACY_POLICY BOOLEAN,
ADD COLUMN AGREE_TERMS_OF_SERVICE BOOLEAN,
ADD COLUMN AGREE_OPERATION_POLICY BOOLEAN;