CREATE TABLE CREATOR_APPLICATION (
    CREATOR_APPLICATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID                BIGINT       NOT NULL,
    SNS_TYPE               VARCHAR(20)  NOT NULL,
    CHANNEL_URL            VARCHAR(512) NOT NULL,
    FOLLOWER_COUNT         INT          NOT NULL,
    BUSINESS_EMAIL         VARCHAR(512) NOT NULL,
    STATUS                 VARCHAR(20)  NOT NULL,
    PROCESSED_AT           DATETIME     NULL,
    REJECT_REASON          VARCHAR(500) NULL,
    CREATED_AT             DATETIME     NOT NULL,
    MODIFIED_AT            DATETIME     NOT NULL,
    CONSTRAINT FK_CREATOR_APPLICATION_USER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
);

CREATE INDEX IDX_CREATOR_APPLICATION_USER_STATUS ON CREATOR_APPLICATION (USER_ID, STATUS);
