-- 반려 시 팔로워 수·업무용 이메일 파기 가능하도록 nullable 변경
-- 신청 연락처는 CREATOR_APPLICATION에 저장 (반려 시 일방향 해시)
ALTER TABLE CREATOR_APPLICATION
    MODIFY COLUMN FOLLOWER_COUNT INT NULL COMMENT '팔로워 수 (반려 시 파기)',
    MODIFY COLUMN BUSINESS_EMAIL VARCHAR(512) NULL COMMENT '업무용 이메일 (반려 시 파기)',
    ADD COLUMN PHONE_NUMBER VARCHAR(128) NULL COMMENT '신청 연락처 (반려 시 일방향 해시)' AFTER BUSINESS_EMAIL;
